version: "3.9"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb27017
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=demo
      - MONGO_INITDB_ROOT_USERNAME=wdh
      - MONGO_INITDB_ROOT_PASSWORD=abc123456
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
      - ./logs:/data/logs
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    command: mongod --config /etc/mongo/mongod.conf
